// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQDbPdVZAKCbdbbUWisHp1lmcsrp2z0TY',
    appId: '1:892675920747:web:eba10ee8b1813594ccb22e',
    messagingSenderId: '892675920747',
    projectId: 'show-ticket-app',
    authDomain: 'show-ticket-app.firebaseapp.com',
    storageBucket: 'show-ticket-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdVoPWBneAGEfaSxfgGt2PFMAa9TM3AV8',
    appId: '1:892675920747:android:307b8fd70ea2ad17ccb22e',
    messagingSenderId: '892675920747',
    projectId: 'show-ticket-app',
    storageBucket: 'show-ticket-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKt35ubl6Zzi0JEXgs4qvKCUGZU2wiPRE',
    appId: '1:892675920747:ios:5e136a2e726247beccb22e',
    messagingSenderId: '892675920747',
    projectId: 'show-ticket-app',
    storageBucket: 'show-ticket-app.firebasestorage.app',
    iosBundleId: 'com.example.showTicketApp',
  );
}
